
const lemonConstants = {
    appName: 'Little Lemon',
    littleLemonRestaurant: 'Little Lemon restaurant',
    intro: 'We are a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist',
    order: 'Order Take Away',
    enterSearch: 'Enter search phrase',
    drinks: 'Drinks',
    deserts: 'Desserts',
    mains: 'Mains',
    continue: 'Continue',
    starter: 'Starters',
    orderForDelivery: 'ORDER FOR DELIVERY!',
    congratulations: 'Congratulations!',
    youHaveRegistered: 'You have registered successfully!',
    personalDetails: 'Personal Information',
    next: 'Next',
    register: 'Register',
    logout: 'Logout',
    getToKnowYou: "Let\'s get to know you",
    logo: 'logo',
    firstName: 'First name',
    email: 'Email',
    emailErrorMessage: 'invalid email',
    emailEmptyError: 'Please enter your email',
    lastNameError: 'Please enter your name',
    lastName: 'Last name',
    firstNameError: 'Please enter your name',
    profile: 'profile picture',
    littleLemon: 'Little Lemon',
    chicago: 'Chicago',
    orderStatuses: 'Order statuses',
    passwordChanges: 'Password changes',
    specialOffers: 'Special offers',
    newsletter: 'Newsletter',
    discardChanges: 'Discard changes',
    saveChanges: 'Save changes',
    emailNotification: 'Email notifications',
    phoneNumber: 'Phone number',
    change: 'Change',
    remove: 'Remove',
    FIRST_NAME: 'FIRST_NAME',
    LAST_NAME: 'LAST_NAME',
    EMAIL: 'EMAIL',
    PROFILE_PICTURE: 'PROFILE_PICTURE'
  };

  export default lemonConstants;